language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t martijnwip/complex-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true martijnwip/complex-test npm test -- --coverage

after_success:
  - docker build -t martijnwip/complex-client ./client
  - docker build -t martijnwip/complex-nginx ./nginx
  - docker build -t martijnwip/complex-server ./server
  - docker build -t martijnwip/complex-worker ./worker
  # log in to the docker CLI

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hub
  - docker push martijnwip/complex-client
  - docker push martijnwip/complex-nginx
  - docker push martijnwip/complex-server
  - docker push martijnwip/complex-worker
